[package]
name = "check_ip"
version = "0.1.0"
authors = ["Bykov Igor <igorb.dev@websm.io>"]

[dependencies]

[dependencies.ipnetwork]
git = "https://github.com/achanda/ipnetwork"
rev = "9920316"
features = ["ipv6-iterator"]
